name: Build

on:
  push:

jobs:
  module:
    name: Build Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create ZIP
        run: |
          make zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tether_unblock-${{ github.run_number }}
          path: tether_unblock-latest.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: tether_unblock-latest.zip
          draft: true

  kernel:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 6

      - name: Check dmesg
        run: |
          set -x
          sudo dmesg

      - name: Build Kernel
        continue-on-error: true
        run: |
          set -x
          docker build \
            --tag ci:${{ github.run_number }} \
            --file ./Dockerfile \
            .

      - name: Check dmesg
        run: |
          set -x
          sudo dmesg
          docker ps -a
          docker images
      - name: Inspect
        run: |
          set -x
          docker image inspect ci:${{ github.run_number }}
      - name: Save tarball
        run: |
          set -x
          docker save ci:${{ github.run_number }} | gzip > ci-${{ github.run_number }}.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci-${{ github.run_number }}
          path: ci-${{ github.run_number }}.tar.gz
