name: Build

on:
  push:

jobs:
  module:
    name: Build Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create ZIP
        run: |
          make zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tether_unblock-${{ github.run_number }}
          path: tether_unblock-latest.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: tether_unblock-latest.zip
          draft: true
